DROP TABLE IF EXISTS `wb_account_open`;
CREATE TABLE `wb_account_open` (
  `id` bigint(15) NOT NULL AUTO_INCREMENT COMMENT 'id',
  `user_number` VARCHAR(50) NOT NULL COMMENT '用户编号',
  `customer_no` VARCHAR(50) NOT NULL COMMENT '商户编号',
  `yp_customer_number` VARCHAR(50) DEFAULT NULL COMMENT '易宝商户编号',
  `account_open_status` VARCHAR(20) NOT NULL COMMENT '开户状态',
  `company_type` VARCHAR(20) NOT NULL COMMENT '商户类型',
  `legal_name` VARCHAR(128) DEFAULT NULL COMMENT '法人姓名',
  `legal_phone_no` VARCHAR(128) DEFAULT NULL COMMENT '法人手机号',
  `legal_id_card` VARCHAR(128) DEFAULT NULL COMMENT '法人身份证号',
  `mer_full_name` VARCHAR(256) DEFAULT NULL COMMENT '商户全称',
  `mer_short_name` VARCHAR(256) DEFAULT NULL COMMENT '商户品牌名称/简称',
  `mer_cert_type` VARCHAR(64) DEFAULT NULL COMMENT '证件类型',
  `mer_cert_no` VARCHAR(128) DEFAULT NULL COMMENT '营业执照证件号',
  `mer_level1_no` VARCHAR(32) DEFAULT NULL COMMENT '商户一级分类编码',
  `mer_level2_no` VARCHAR(32) DEFAULT NULL COMMENT '商户二级分类编码',
  `mer_province_code` VARCHAR(32) DEFAULT NULL COMMENT '商户经营地址所在省',
  `mer_province_name` VARCHAR(128) DEFAULT NULL COMMENT '商户经营地址所在省名称',
  `mer_city_code` VARCHAR(32) DEFAULT NULL COMMENT '商户经营地址所在市',
  `mer_city_code` VARCHAR(128) DEFAULT NULL COMMENT '商户经营地址所在市名称',
  `mer_district_code` VARCHAR(32) DEFAULT NULL COMMENT '商户经营地址所在区',
  `mer_district_code` VARCHAR(128) DEFAULT NULL COMMENT '商户经营地址所在区名称',
  `mer_address` VARCHAR(512) DEFAULT NULL COMMENT '商户经营地址所在具体地址',
  `mer_contact_name` VARCHAR(64) DEFAULT NULL COMMENT '商户联系人姓名',
  `mer_contact_phone` VARCHAR(128) DEFAULT NULL COMMENT '商户联系人手机',
  `mer_contact_email` VARCHAR(128) DEFAULT NULL COMMENT '商户联系人邮箱',
  `tax_regist_cert` VARCHAR(256) DEFAULT NULL COMMENT '税务登记证编号',
  `account_license` VARCHAR(64) DEFAULT NULL COMMENT '开户许可证编号',
  `org_code` VARCHAR(256) DEFAULT NULL COMMENT '组织机构代码',
  `is_org_code_long` INTEGER(1) DEFAULT NULL COMMENT '组织机构代码证是否长期有效',
  `org_code_expiry` DATE DEFAULT NULL COMMENT '组织机构代理证有效期',
  `mer_scope` VARCHAR(1024) DEFAULT NULL COMMENT '商户经营范围',
  `settle_card_number` VARCHAR(128) DEFAULT NULL COMMENT '结算银行账号或者银行卡号',
  `head_bank_code` VARCHAR(256) DEFAULT NULL COMMENT '开户行总行编码',
  `head_bank_name` VARCHAR(256) DEFAULT NULL COMMENT '开户行总行名称',
  `bank_code` VARCHAR(256) DEFAULT NULL COMMENT '开户行支行编码',
  `bank_province_code` VARCHAR(32) DEFAULT NULL COMMENT '开户省编码',
  `bank_city_code` VARCHAR(32) DEFAULT NULL COMMENT '开户市编码',
  `product_info` VARCHAR(2048) DEFAULT NULL COMMENT '开通产品',
  `file_info` VARCHAR(4000) DEFAULT NULL COMMENT '资质影印件',
  `mer_authorize_type` VARCHAR(32) DEFAULT NULL COMMENT '授权类型',
  `open_lbs` VARCHAR(50) DEFAULT NULL COMMENT '坐标',
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `user_number` (`user_number`),
  INDEX `customer_no` (`customer_no`),
  INDEX `yp_customer_number` (`yp_customer_number`),
  INDEX `create_time` (`create_time`),
  INDEX `update_time` (`update_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='`开户表`';