-- auto Generated on 2017-09-18 17:11:59 
-- DROP TABLE IF EXISTS `wb_order`; 
CREATE TABLE `wb_order`(
    `id` VARCHAR (50) NOT NULL COMMENT '系统唯一流水号',
    `version` BIGINT (15) NOT NULL DEFAULT 0 COMMENT '版本号',
    `customer_number` VARCHAR (50) NOT NULL  DEFAULT '' COMMENT 'customerNumber',
    `request_no` VARCHAR (64)  DEFAULT '' COMMENT '商户订单号',
    `yeepay_order_id` VARCHAR (50) DEFAULT '' COMMENT '易宝订单号',
    `user_number` VARCHAR (50)  DEFAULT '' COMMENT 'userNumber',
    `qr_id` VARCHAR (50)  DEFAULT '' COMMENT '二维码id',
    `token` VARCHAR(128)  DEFAULT '' COMMENT '订单token',
    `pay_type` VARCHAR(50)  DEFAULT '' COMMENT '支付类型',
    `order_type` VARCHAR (50)  DEFAULT '' COMMENT '订单类型',
    `scan_type` VARCHAR (50)  DEFAULT '' COMMENT 'scanType',
    `order_status` VARCHAR (50)  DEFAULT '' COMMENT 'orderStatus',
    `trx_amt` DECIMAL (12,2)  DEFAULT 0.0 COMMENT 'trxAmt',
    `real_amount` DECIMAL (12,2)  DEFAULT 0.0 COMMENT 'realAmount',
    `fee_amount` DECIMAL (12,2)  DEFAULT 0.0 COMMENT 'feeAmount',
    `refund_amount` DECIMAL (12,2)  DEFAULT 0.0 COMMENT 'refundAmount',
    `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP  COMMENT 'createTime',
    `complete_time` TIMESTAMP  DEFAULT CURRENT_TIMESTAMP COMMENT 'completeTime',
    `update_time` TIMESTAMP  DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'updateTime',
    `err_code` VARCHAR (20)  DEFAULT '' COMMENT '错误码',
    `err_message` VARCHAR (128)  DEFAULT '' COMMENT '错误信息',
    `remark` VARCHAR (128)  DEFAULT '' COMMENT 'remark',
    INDEX(id),
    INDEX(request_no),
    INDEX(token),
    INDEX(yeepay_order_id),
    INDEX(user_number),
    INDEX(create_time),
    INDEX(complete_time),
    INDEX(update_time),
    PRIMARY KEY (`id`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT '`wb_order`';